#!/bin/sh
libnames=`cd lib ; ls -1 | grep '\.[0-9][0-9]*\.dylib$'`
changes=''
for dep in ${libnames} ; do
    changes="${changes} -change ${4}/${dep} ${3}/${dep}"
done
for i in ${libnames} ; do
    install_name_tool ${changes} -id ${3}/${i} ${1}/${i}
done

if test -f "${2}/wxrc-3.3" ; then
    install_name_tool ${changes} ${2}/wxrc-3.3
fi
